### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by brandonb1987** [vahempio/Tasmota-for-eWeLink#4]
Can you update to the latest 12.0.2? I've tried building it with your code changes and I cant seem to get it to compile. May be an issue on my end only.

If you manage to get it working, can you update the .bin for us not-so-tech-savy?

**Comment by nao-pon** [comment]
Many thanks to master vahempio. Here's what I build and now using.

[tasmota32-v12.0.2-EWELINK.bin.zip](https://github.com/vahempio/Tasmota-for-eWeLink/files/9357601/tasmota32-v12.0.2-EWELINK.bin.zip)

ref. repo. https://github.com/nao-pon/Tasmota/tree/ewelink-eth

**Comment by vahempio** [comment]
Hi and sorry for the long response delay due to holidays!
FYI, the 12.0.1 version is already present but in another branch, you can find it here: https://github.com/vahempio/Tasmota-for-eWeLink/tree/tasmota-vahempio/bin
I will post new versions but only on major increments in the future. Except if you find something or a bugfix present in a newer version?

I close the issue because everything seems ok based on my builds and nao-pon's comment. Thanks to you, do not hesitate to put another comment if I miss something in your initial point.
